default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  arm_joint1:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
  arm_joint2:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
  arm_joint3:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
  arm_joint4:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
  arm_joint5:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
  arm_joint6:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: true
    max_acceleration: 6.28318
