flipper_driver:
  ros__parameters:
    port_name: "/dev/ttyUSB0"  # udev: deploy/99-robot.rules の dynamixel_flipper symlink
    baud_rate: 115200 # 通信速度。要check
    dynamixel_ids: [2, 4, 3, 1]
    watchdog_timeout_ms: 500
