slam_toolbox:
  ros__parameters:

    # ── 基本フレーム設定 ──
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: false # Launchで上書き

    # ── SLAMモード ──
    # 本当にこれで良いかは謎
    mode: mapping # 初期地図作成用に mapping

    # /scan は pointcloud_to_laserscan 側が Best Effort で publish するため、
    # SLAM 側 subscription も合わせる。
    qos_overrides:
      /scan:
        subscription:
          reliability: best_effort
          durability: volatile

    # ── Solver設定 ──
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
