slam_toolbox:
  ros__parameters:

    # ── 基本フレーム設定 ──
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: false # Launchで上書き

    # ── SLAMモード ──
    # 本当にこれで良いかは謎
    mode: mapping # 初期地図作成用に mapping
    use_bond: false

    # /scan は Gazebo からの LaserScan 直ブリッジで受ける。
    qos_overrides:
      /scan:
        subscription:
          reliability: reliable
          durability: volatile

    # CPU負荷が高い環境でのタイムジャンプ対策
    minimum_time_interval: 0.5
    transform_publish_period: 0.1

    # ── Solver設定 ──
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
